# Generated by Django 4.2.1 on 2023-07-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_best_score_user_best_score_landmarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scans_left',
            field=models.IntegerField(default=5),
        ),
    ]
