version: '3'

services:
  redis:
    image: redis:7.0
  
  api: &api
    platform: linux/amd64
    build: 
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celeryworker:
    <<: *api
    ports: []
    command: poetry run celery -A api worker -l info
    depends_on:
      - api
  