# Generated by Django 4.1.7 on 2023-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='era',
            name='era_name',
            field=models.CharField(default='New Era', max_length=200),
        ),
        migrations.AlterField(
            model_name='era',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='era_images'),
        ),
        migrations.AlterField(
            model_name='historytimeline',
            name='timeline_name',
            field=models.CharField(default='New Timeline', max_length=200),
        ),
    ]
