# Generated by Django 4.2.1 on 2023-06-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historytimeline',
            options={'ordering': ('timeline_start',)},
        ),
    ]
