# Generated by Django 4.1.7 on 2023-05-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_era_era_name_alter_era_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='era',
            name='era_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historytimeline',
            name='timeline_name',
            field=models.CharField(max_length=200),
        ),
    ]
