# Generated by Django 4.1.7 on 2023-05-11 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_alter_era_era_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='era',
            name='history_timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eras', to='timeline.historytimeline'),
        ),
    ]
