# Generated by Django 4.2.1 on 2023-05-24 09:40

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monument',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='monument',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monument',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='monument',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
