# Generated by Django 4.2.1 on 2023-05-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0002_article_monuments'),
        ('monuments', '0002_alter_monument_options_monument_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMonument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monuments.monument')),
            ],
        ),
    ]
