# Generated by Django 4.2.1 on 2023-05-24 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0002_article_monuments'),
        ('monuments', '0003_articlemonument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemonument',
            name='article',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='article_monuments', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='articlemonument',
            name='monument',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='article_monuments', to='monuments.monument'),
        ),
    ]
