# Generated by Django 4.2.1 on 2023-06-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0004_alter_articlemonument_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monument',
            options={'ordering': ('-updated',)},
        ),
    ]
