# Generated by Django 4.2.1 on 2023-06-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0004_alter_articlemonument_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monument',
            options={'ordering': ('-updated',)},
        ),
        migrations.AddField(
            model_name='monument',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
