# Generated by Django 4.2.1 on 2023-07-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0005_alter_monument_options'),
        ('monuments', '0006_monument_model_obj_monument_model_texture'),
    ]

    operations = [
    ]
