# Generated by Django 4.2.1 on 2023-07-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0007_merge_20230701_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
