# Generated by Django 4.2.1 on 2023-07-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0008_monument_date_monument_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='monuments_images/'),
        ),
    ]
