# Generated by Django 4.2.1 on 2023-07-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
    ]
