# Generated by Django 4.1.7 on 2023-03-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='title',
            new_name='article_title',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='description',
        ),
        migrations.AddField(
            model_name='articles',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Article.section'),
        ),
    ]
