# Generated by Django 4.1.7 on 2023-04-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_section_rename_title_articles_article_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Article.articles'),
        ),
    ]
