# Generated by Django 4.2.1 on 2023-05-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_chocie',
            new_name='correct_choice',
        ),
    ]
