# Generated by Django 4.1.7 on 2023-03-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_check', '0002_alter_choice_choice_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(related_name='choices', to='knowledge_check.choice'),
        ),
    ]
