# Generated by Django 4.1.7 on 2023-03-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_check', '0003_remove_choice_question_question_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='imgae',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
