# Generated by Django 4.1.7 on 2023-03-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_check', '0004_rename_imgae_question_image_alter_choice_choice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(choices=[('statues', 'statues'), ('monuments', 'monuments'), ('landmarks', 'landmarks')], max_length=200),
        ),
    ]
